apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: llm-guard-settings
    namespace: llm-guard
    behavior: replace
    envs:
      - local-config.env

secretGenerator:
  - name: llm-guard-secret
    namespace: llm-guard
    behavior: replace
    type: Opaque
    literals:
      - SAFE_REPLY_MESSAGE="[LOCAL TEST] 触发安全拦截！"

patches:
  - path: patches-local.yaml